# Generated by Django 5.0.4 on 2024-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpagegalleryimage'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='ArticleGalleryImage',
        ),
    ]
